# Generated by Django 2.1.4 on 2018-12-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_platform', '0002_auto_20181212_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
    ]
