# Generated by Django 2.1.4 on 2018-12-12 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_platform', '0005_auto_20181212_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog_platform.Post'),
            preserve_default=False,
        ),
    ]
