# Generated by Django 2.1.4 on 2018-12-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_platform', '0006_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
