# Generated by Django 2.1.4 on 2018-12-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_platform', '0007_auto_20181212_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AddField(
            model_name='post',
            name='page_views',
            field=models.IntegerField(default=0),
        ),
    ]
